create table PELICULAS
(
  CODIGO_PELICULA INTEGER not null,
  NOMBRE          VARCHAR2(170) not null,
  DIRECTOR        VARCHAR2(50) not null,
  GENERO          VARCHAR2(15) not null,
  ESTRENO         CHAR(1) not null,
  PUBLICO         CHAR(1) not null,
  FECHA_INSERCION VARCHAR2(50) not null,
  IMAGEN          VARCHAR2(200)
)
;
alter table PELICULAS
  add primary key (CODIGO_PELICULA);
alter table PELICULAS
  add unique (NOMBRE);


insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (1, 'EL GOLPE', 'GEORGE ROY HILL', 'COMEDIA', '0', '1', '2007-05-27', 'El_golpe.jpg');
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (2, 'LOS PAJAROS', 'ALFRED HITCHOCK', 'TERROR', '0', '0', '2007-05-27', 'Los pajaros.jpg');
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (3, 'SOSPECHOSOS HABITUALES', 'BRYAN SINGER', 'SUSPENSE', '0', '0', '2007-05-27', 'sospechosos_habituales.jpg');
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (4, 'PIRATAS DEL CARIBE. EN EL FIN DEL MUNDO', 'GORE VERBINSKI', 'AVENTURAS', '1', '1', '2007-05-27', 'piratas3.jpg');
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (5, 'EL SEÑOR LOS DE LOS ANILLOS. LA COMUNIDAD DEL ANIL', 'PETER JACKSON', 'AVENTURAS', '0', '1', '2007-05-27', 'señor-anillos-1.jpg');
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (6, 'WILLOW', 'RON HOWARD ', 'AVENTURAS', '0', '1', '2007-05-27', 'willow.jpg');
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (7, 'BRAVEHEART', 'MEL GIBSON', 'AVENTURAS', '0', '0', '2007-05-27', 'Braveheart.jpg');
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (8, 'ALIEN, EL OCTAVO PASAJERO', 'RIDLEY SCOTT ', 'TERROR', '0', '0', '2007-05-27', null);
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (9, 'HOTEL RWANDA', 'TERRY GEORGE', 'DRAMA', '0', '0', '2007-05-27', null);
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (10, 'CRASH (COLISIÓN)', 'PAUL HAGGIS', 'DRAMA', '0', '0', '2007-05-27', null);
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (11, 'EL TEMIBLE BURLON', 'ROBERT SIODMAK', 'AVENTURAS', '0', '1', '2007-05-27', null);
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (12, 'EL NUMERO 23', 'JOEL SCHUMACHER', 'SUSPENSE', '1', '1', '2007-05-27', null);
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (13, 'BEN-HUR', 'WILLIAM WYLER ', 'DRAMA', '0', '0', '2007-05-27', null);
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (14, 'SHREK 3', 'CHRIS MILLER', 'COMEDIA', '1', '1', '2007-05-27', null);
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (15, 'LA LISTA DE SHILDER ', 'STEVEN SPIELBERG', 'DRAMA', '0', '0', '2007-05-27', null);
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (16, 'LA GRAN EVASION', 'JOHN STURGES', 'BELICA', '0', '1', '2007-05-27', null);
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (17, 'DOCE DEL PATIBULO', 'ROBERT ALDRICH', 'BELICA', '0', '0', '2007-05-27', null);
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (18, 'DOCE MONOS', 'TERRY GILLIAM', 'SUSPENSE', '1', '0', '2007-05-27', null);
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (19, 'AL ESTE DEL EDEN', 'ELIA KAZAN ', 'DRAMA', '0', '0', '2007-05-27', null);
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (20, 'TIBURON', 'STEVEN SPIELBERG', 'TERROR', '0', '0', '2007-05-27', null);
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (21, 'MATRIX', ' LARRY Y ANDY WACHOWSKI', 'CIENCIA FICCION', '0', '1', '2007-05-27', null);
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (22, 'AMERICAN HISTORY X', 'TONY KAYE', 'DRAMA', '0', '0', '2007-05-27', null);
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (24, 'MOSNTER', 'SS', 'AVENTURAS', '1', '1', '2007-05-27', 'monstruos_sa_2001.jpg');
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (26, 'MAs miedo', 'ALFRED HITCHOCK', 'TERROR', '0', '0', 'Mon Jun 16 01:01:11 CEST 2014', 'No disponible..');
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (27, 'tercer Miedo', 'ALFRED HITCHOCK', 'TERROR', '0', '0', 'Mon Jun 16 01:01:50 CEST 2014', 'No disponible..');
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (28, 'Miedo4', 'ALFRED HITCHOCK', 'TERROR', '0', '0', 'Mon Jun 16 01:04:08 CEST 2014', 'No disponible..');
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (29, 'comedia1', 'RIDLEY SCOTT ', 'COMEDIA', '0', '0', 'Mon Jun 16 01:14:30 CEST 2014', 'No disponible..');
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (30, 'que miedo?', 'RIDLEY SCOTT ', 'TERROR', '0', '0', 'Mon Jun 16 01:15:16 CEST 2014', 'No disponible..');
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (31, 'GAlaxia 1', 'RIDLEY SCOTT ', 'CIENCIA FICCION', '1', '0', 'Mon Jun 16 01:24:08 CEST 2014', 'No disponible..');
insert into PELICULAS (CODIGO_PELICULA, NOMBRE, DIRECTOR, GENERO, ESTRENO, PUBLICO, FECHA_INSERCION, IMAGEN)
values (25, 'Miedo', 'ALFRED HITCHOCK', 'TERROR', '0', '0', 'Mon Jun 16 00:58:54 CEST 2014', 'No disponible..');
commit;
