package BD;

import BD.GestionaBd;
import ES.ES;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class Conectate extends javax.swing.JDialog {

    /**
     * Creates new form Conectate
     * 
     */
      String usuario,bd,servidor;
      String contrasena;
      public GestionaBd connBd = null;
     
    public Conectate(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocation(300, 270);
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        alumno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        servidorr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        contrasenaa = new javax.swing.JPasswordField();
        jC_tipoBd = new javax.swing.JComboBox<>();
        namaBd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("Usuario:");

        alumno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alumno.setName("usuario"); // NOI18N
        alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Contraseña");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Base de Datos:");
        jLabel3.setToolTipText("");

        servidorr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        servidorr.setText("localhost");
        servidorr.setToolTipText("");
        servidorr.setName("servidorr"); // NOI18N
        servidorr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                servidorrMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Servidor:");
        jLabel4.setToolTipText("");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("<< Conectar >>");
        jButton1.setToolTipText("");
        jButton1.setName("conectar"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Datos de Conexión ");
        jLabel5.setToolTipText("");

        contrasenaa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contrasenaa.setName("contrasenaa"); // NOI18N

        jC_tipoBd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jC_tipoBd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MySql", "Oracle" }));

        namaBd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaBd.setText("instituto");
        namaBd.setToolTipText("");
        namaBd.setName("servidorr"); // NOI18N
        namaBd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namaBdMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nombre de la Base de Datos:");
        jLabel6.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(servidorr, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jC_tipoBd, 0, 151, Short.MAX_VALUE)
                            .addComponent(contrasenaa)
                            .addComponent(alumno)
                            .addComponent(namaBd)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jButton1)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(contrasenaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jC_tipoBd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(namaBd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servidorr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alumnoActionPerformed

    private void servidorrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servidorrMouseClicked
        System.out.println(" Se pulso conectar..");// TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_servidorrMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int opcion=0;
        
      //   do{
         
            usuario     = alumno.getText();
            contrasena  =contrasenaa.getText();
            bd          =  (String)this.jC_tipoBd.getSelectedItem();
            
            servidor    =servidorr.getText();
            String nombreBd      =namaBd.getText();

            connBd = new BD.GestionaBd(bd, servidor,nombreBd, usuario, contrasena);
            if (connBd.getConn() == null) {//JOptioPane

                     opcion=JOptionPane.showConfirmDialog(rootPane, "No se ha podido conectar a la Bd ( qieres reintentar )? ", 
                                                  "Error de Conexión!!!!",JOptionPane.YES_NO_OPTION,JOptionPane.ERROR_MESSAGE);
                    }
       //     } while (connBd.getConn() == null && (opcion ==0));
      
         
        if (connBd.getConn() == null&& (opcion ==1)) {
           JOptionPane.showMessageDialog(rootPane, "Sin conexion, Fin de la aplicación");
            System.exit(0);
        }
        else if(connBd.getConn() != null)
            this.setVisible(false);//pasar valores a bdd
    }//GEN-LAST:event_jButton1ActionPerformed

    private void namaBdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaBdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_namaBdMouseClicked
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alumno;
    private javax.swing.JPasswordField contrasenaa;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jC_tipoBd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField namaBd;
    private javax.swing.JTextField servidorr;
    // End of variables declaration//GEN-END:variables
}
