/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sw_Componentes_21;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Usuario
 */
public class LoginBD extends javax.swing.JDialog implements DocumentListener, FocusListener {
    Connection conn;

    /**
     * Creates new form LoginBD
     */
    public LoginBD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        jT_usuario.getDocument().putProperty("owner", jT_usuario);
        jP_contraseña.getDocument().putProperty("owner", jP_contraseña);
        
        jT_usuario.getDocument().putProperty("etiqueta", jL_usuario);
        jP_contraseña.getDocument().putProperty("etiqueta", jL_contraseña);
        
        jT_usuario.setName("usuario"); jP_contraseña.setName("contraseña");
        
        jT_usuario.getDocument().addDocumentListener(this);
        jP_contraseña.getDocument().addDocumentListener(this);
        
        jT_usuario.addFocusListener(this);
         jP_contraseña.addFocusListener(this);
         
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jB_conectar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jT_ServidorBd = new javax.swing.JTextField();
        jT_nombreBd = new javax.swing.JTextField();
        jC_sgbd = new javax.swing.JComboBox<>();
        jL_sgbd = new javax.swing.JLabel();
        jT_usuario = new javax.swing.JTextField();
        jL_usuario = new javax.swing.JLabel();
        jL_contraseña = new javax.swing.JLabel();
        jP_contraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("usuario:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("contraseña:");

        jB_conectar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jB_conectar.setForeground(new java.awt.Color(255, 0, 0));
        jB_conectar.setText("Conectar");
        jB_conectar.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Base de Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 102, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("Tipo :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 28, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 51));
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setText("Servidor:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 110, -1, -1));

        jT_ServidorBd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jT_ServidorBd.setText("localhost");
        jPanel1.add(jT_ServidorBd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 158, -1));

        jT_nombreBd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jT_nombreBd.setText("scott");
        jT_nombreBd.setToolTipText("");
        jPanel1.add(jT_nombreBd, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 69, 158, -1));

        jC_sgbd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jC_sgbd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija SGBD", "MySql", "Oracle" }));
        jPanel1.add(jC_sgbd, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 28, 158, -1));

        jL_sgbd.setForeground(new java.awt.Color(255, 0, 0));
        jL_sgbd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_sgbd.setText("*Sgbd Obligatorio");
        jPanel1.add(jL_sgbd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 250, -1));

        jT_usuario.setColumns(20);
        jT_usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jT_usuario.setToolTipText("");

        jL_usuario.setForeground(new java.awt.Color(255, 0, 0));
        jL_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_usuario.setText("*Usuario Obligatorio");

        jL_contraseña.setForeground(new java.awt.Color(255, 0, 0));
        jL_contraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_contraseña.setText("*Contraseña Obligatorio");

        jP_contraseña.setColumns(12);
        jP_contraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jP_contraseña))
                                .addComponent(jL_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(44, 44, 44)
                                    .addComponent(jT_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jL_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jB_conectar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jT_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jL_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jP_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_contraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jB_conectar)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_conectar;
    private javax.swing.JComboBox<String> jC_sgbd;
    private javax.swing.JLabel jL_contraseña;
    private javax.swing.JLabel jL_sgbd;
    private javax.swing.JLabel jL_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jP_contraseña;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jT_ServidorBd;
    private javax.swing.JTextField jT_nombreBd;
    private javax.swing.JTextField jT_usuario;
    // End of variables declaration//GEN-END:variables

    public static Connection obtieneConexion(String tipoBd, String servidor, String nombreBd, String usuario, String contraseña) {
        Connection conn = null;
        String url = "";
        try {
            if(tipoBd.equalsIgnoreCase("Oracle")) {
                DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver() );
                url = "jdbc:oracle:thin:@" + servidor + ":1521:" + nombreBd;
            } else {
                DriverManager.registerDriver(new com.mysql.jdbc.Driver() );
                url = "jdbc:mysql://" + servidor + "/" + nombreBd;
            }
            conn = DriverManager.getConnection(url, usuario, contraseña);
        } catch (SQLException ex) {
            System.out.println("Error conectando con la base de datos -> " + ex.getMessage() );
        }
        return conn;
    }

    @Override
    public void insertUpdate(DocumentEvent e) {
        campoVacio(e);
        
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
         campoVacio(e);
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        
    }
    //-----------------------------------------------------
    void campoVacio(DocumentEvent e){
        JTextField campo =(JTextField)e.getDocument().getProperty("owner");
        JLabel     etiqueta =(JLabel)e.getDocument().getProperty("etiqueta");
        String texto    =campo.getText();
        int    longitud =texto.length();
        String nombre   =campo.getName();
        
        if(longitud==0){
            etiqueta.setText("El/la "+nombre+" no puede estar vacío/a");
            etiqueta.setVisible(true);
   /*     switch(nombre){
            case "jT_usuario":
                jL_usuario
            break; 
            case "jP_contraseña":
                jP_usuario
            break; 
        }*/
        }//if....
        else etiqueta.setVisible(false);
        
    }//campoVacio...
    //----------------------------------------

    @Override
    public void focusGained(FocusEvent e) {
        
    }

    @Override
    public void focusLost(FocusEvent e) {
      JTextField campo =(JTextField)e.getSource();
      String texto    =campo.getText();
      
       if(campo.getText().length()==0){
           
         switch(campo.getName()){
             case "usuario":
               if(!texto.matches("^([A-Z])(?=.*[a-z])(?=.*\\d)(?!.*[A-Z])\\w{5,}$")){
                   jL_usuario.setText("Formato de usuario erroneo");
                   jL_usuario.setVisible(true);
                   campo.setToolTipText("^([A-Z])(?=.*[a-z])(?=.*\\d)(?!.*[A-Z])\\w{5,}$");
               }
            break; 
            case "contraseña":
                if(!texto.matches("^([A-Z])(?=.*[a-z])(?=.*\\d)(?!.*[A-Z])\\w{5,}$")){
                   jL_contraseña.setText("Formato de pw erroneo");
                   jL_contraseña.setVisible(true);
                   campo.setToolTipText("^([A-Z])(?=.*[a-z])(?=.*\\d)(?!.*[A-Z])\\w{5,}$");
               }
            break; 
             
         }
      
    }
 
    }
    
}    
